package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"ByDishBackend/graph/model"
	"ByDishBackend/service"
	"context"
)

// Menu is the resolver for the menu field.
func (r *queryResolver) Menu(ctx context.Context, input *model.MenuInput) (*model.Menu, error) {
	return service.FindMenu(*input.ID), nil
}

// MenuList is the resolver for the menuList field.
func (r *queryResolver) MenuList(ctx context.Context, input *model.MenuListInput) ([]*model.Menu, error) {
	return service.QueryMenu(input), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
