// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dish struct {
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Pic         string  `json:"pic"`
	Freq        int     `json:"freq"`
	IntType     int     `json:"intType"`
	Description string  `json:"description"`
	Avb         int     `json:"avb"`
}

type DishInput struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Pic         *string `json:"pic,omitempty"`
	Freq        *int    `json:"freq,omitempty"`
	IntType     *int    `json:"intType,omitempty"`
	Description *string `json:"description,omitempty"`
	Avb         *int    `json:"avb,omitempty"`
	Label       *string `json:"label,omitempty"`
	PageNo      *int    `json:"pageNo,omitempty"`
	PageSize    *int    `json:"pageSize,omitempty"`
}

type Menu struct {
	ID      string    `json:"id"`
	Time    *string   `json:"time,omitempty"`
	List    []*string `json:"list,omitempty"`
	Name    *string   `json:"name,omitempty"`
	TypeInt *int      `json:"typeInt,omitempty"`
}

type MenuInput struct {
	ID *string `json:"id,omitempty"`
}

type MenuListInput struct {
	PageNo   int     `json:"pageNo"`
	PageSize int     `json:"pageSize"`
	Name     *string `json:"name,omitempty"`
	TypeInt  *int    `json:"typeInt,omitempty"`
	Time     *string `json:"time,omitempty"`
}

type MutationResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}
