// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddMenuInput struct {
	Name     string         `json:"name"`
	DishList []*DishObjsVal `json:"dishList"`
}

type Dish struct {
	ID          string    `json:"id"`
	Name        *string   `json:"name,omitempty"`
	Pic         *string   `json:"pic,omitempty"`
	Freq        *int      `json:"freq,omitempty"`
	IntType     *int      `json:"intType,omitempty"`
	Description *string   `json:"description,omitempty"`
	Avb         *int      `json:"avb,omitempty"`
	Label       []*string `json:"label,omitempty"`
}

type DishInput struct {
	ID          *string   `json:"id,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Pic         *string   `json:"pic,omitempty"`
	Freq        *int      `json:"freq,omitempty"`
	IntType     *int      `json:"intType,omitempty"`
	Description *string   `json:"description,omitempty"`
	Avb         *int      `json:"avb,omitempty"`
	Label       []*string `json:"label,omitempty"`
	PageNo      *int      `json:"pageNo,omitempty"`
	PageSize    *int      `json:"pageSize,omitempty"`
	Objs        []*string `json:"objs,omitempty"`
}

type DishListResponse struct {
	PageNo     *int    `json:"pageNo,omitempty"`
	TotalPages *int    `json:"totalPages,omitempty"`
	Data       []*Dish `json:"data,omitempty"`
}

type DishObjsVal struct {
	DishID string       `json:"dishId"`
	ObjArr []*ObjValRel `json:"objArr"`
}

type Menu struct {
	ID      string          `json:"id"`
	Time    *string         `json:"time,omitempty"`
	List    []*TDishObjsVal `json:"list,omitempty"`
	Name    *string         `json:"name,omitempty"`
	TypeInt *int            `json:"typeInt,omitempty"`
}

type MenuInput struct {
	ID *string `json:"id,omitempty"`
}

type MenuListInput struct {
	PageNo   int     `json:"pageNo"`
	PageSize int     `json:"pageSize"`
	Name     *string `json:"name,omitempty"`
	TypeInt  *int    `json:"typeInt,omitempty"`
	Time     *string `json:"time,omitempty"`
}

type MenuListResponse struct {
	PageNo     *int    `json:"pageNo,omitempty"`
	TotalPages *int    `json:"totalPages,omitempty"`
	Data       []*Menu `json:"data,omitempty"`
}

type MutationResponse struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

type ObjValContent struct {
	Valid string `json:"valid"`
	Label string `json:"label"`
	Val   int    `json:"val"`
}

type ObjValList struct {
	ObjID   string           `json:"objId"`
	ValList []*ObjValContent `json:"valList"`
}

type ObjValRel struct {
	ObjID string `json:"objId"`
	ValID string `json:"valId"`
}

type TDishObjsVal struct {
	DishID   string        `json:"dishId"`
	DishName string        `json:"dishName"`
	ObjArr   []*TObjValRel `json:"objArr"`
}

type TObjValRel struct {
	ObjID   string  `json:"objId"`
	ObjName *string `json:"objName,omitempty"`
	Label   *string `json:"label,omitempty"`
	ValID   string  `json:"valId"`
}
