// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Menu struct {
	ID      string    `json:"id"`
	Time    *string   `json:"time,omitempty"`
	List    []*string `json:"list,omitempty"`
	Name    *string   `json:"name,omitempty"`
	TypeInt *int      `json:"typeInt,omitempty"`
}

type MenuInput struct {
	ID *string `json:"id,omitempty"`
}

type MenuListInput struct {
	PageNo   int     `json:"pageNo"`
	PageSize int     `json:"pageSize"`
	Name     *string `json:"name,omitempty"`
	TypeInt  *int    `json:"typeInt,omitempty"`
	Time     *string `json:"time,omitempty"`
}
